In [1]:
import numpy as np

arr = np.array([[0, 1], [2, 3]])
print("Original flattened array:\n", arr)

flat = arr.flatten()
print("Maximum value of the above flattened array:", flat.max())
print("Minimum value of the above flattened array:", flat.min())


Original flattened array:
 [[0 1]
 [2 3]]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [2]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 Matrix with values from 2 to 10:\n", matrix)


3x3 Matrix with values from 2 to 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

float_arr = arr.astype(float)
print("Array converted to a float type:", float_arr)


Original array: [1 2 3 4]
Array converted to a float type: [1. 2. 3. 4.]


In [4]:
import numpy as np

A = np.array([[1, 2], [0, 1]])
B = np.array([[2, 1], [1, 0]])

result = np.dot(A, B)
transpose = result.T

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result of A x B:\n", result)
print("Transpose of the resultant matrix:\n", transpose)



Matrix A:
 [[1 2]
 [0 1]]
Matrix B:
 [[2 1]
 [1 0]]
Result of A x B:
 [[4 1]
 [1 0]]
Transpose of the resultant matrix:
 [[4 1]
 [1 0]]


In [5]:
import numpy as np

matrix = np.array([
    [6, 1, 1, 3],
    [4, -2, 5, 1],
    [2, 8, 7, 6],
    [3, 1, 9, 7]
])

inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:\n", matrix)
print("Inverse of Matrix:\n", inverse_matrix)


Original Matrix:
 [[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
Inverse of Matrix:
 [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
